# Generated by Django 2.2.4 on 2019-11-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.IntegerField(default=0),
        ),
    ]
